language: objective-c
osx_image: xcode12.3

script:
  - xcodebuild test -project ShopProject/ShopProject.xcodeproj -scheme ShopProject -destination "platform=iOS Simulator,name=iPhone 12" -sdk iphonesimulator14.3 CODE_SIGNING_REQUIRED=NO
